--- # run the flying
- name: run -> create the conf directory
  file:
    path: /etc/shadowsocks-libev
    state: directory
    mode: '0744'

- name: run -> add the server conf file
  template:
    src: server-config.json.j2
    dest: /etc/shadowsocks-libev/server-config.json

- name: run -> firewall enable tcp
  firewalld:
    port: "{{ open_port }}/tcp"
    zone: public
    permanent: yes
    state: enabled

- name: run -> firewall enable udp
  firewalld:
    port: "{{ open_port }}/udp"
    zone: public
    permanent: yes
    state: enabled

- name: run -> restart the firewall
  service:
    name: firewalld
    state: restarted
    
- name: run -> start the flying
  shell: nohup ss-server -c /etc/shadowsocks-libev/server-config.json &

- name: run -> check if the codes exist
  stat:
    path: "{{ kcptun_path }}/kcptun.tar.gz"
  register: kcptun_codes

- name: run -> download the kcptun codes
  get_url:
    url: "{{ kcptun_url }}"
    dest: "{{ kcptun_path }}/kcptun.tar.gz"
  when: not kcptun_codes.stat.exists

- name: run -> unarchive the package
  unarchive:
    remote_src: yes
    src: "{{ kcptun_path }}/kcptun.tar.gz"
    dest: "{{ kcptun_path }}"

- name: run -> add the kcptun conf file
  template:
    src: server-config.json.j2
    dest: "{{ kcptun_path }}/kcptun-config.json"

- name: run -> start the kcptun
  shell: nohup /usr/local/kcptun/server_linux_amd64 -c /usr/local/kcptun/kcptun-config.json &
