--- # run the flying
- name: run -> create the conf directory
  file:
    path: /etc/shadowsocks-libev
    state: directory
    mode: '0744'

- name: run -> add the server conf file
  template:
    src: server-config.json.j2
    dest: /etc/shadowsocks-libev/server-config.json

- name: run -> firewall enable
  service:
    name: firewalld
    state: started
    enabled: yes

- name: run -> firewall add tcp port
  command: firewall-cmd --permanent --zone=public --add-port={{ open_port }}/tcp

- name: run -> firewall add udp port
  command: firewall-cmd --permanent --zone=public --add-port={{ open_port }}/udp

- name: run -> firewall reload
  service:
    name: firewalld
    state: reloaded

- name: run -> start the flying
  shell: nohup ss-server -c /etc/shadowsocks-libev/server-config.json &

- name: run -> create the kcptun directory
  file:
    path: "{{ kcptun_path }}"
    state: directory
    owner: '0744'

- name: run -> download the kcptun codes
  get_url:
    url: "{{ kcptun_url }}"
    dest: "{{ kcptun_path }}/kcptun.tar.gz"

- name: run -> unarchive the package
  unarchive:
    remote_src: yes
    src: "{{ kcptun_path }}/kcptun.tar.gz"
    dest: "{{ kcptun_path }}"

- name: run -> add the kcptun conf file
  template:
    src: kcptun-config.json.j2
    dest: "{{ kcptun_path }}/kcptun-config.json"

- name: run -> start the kcptun
  shell: nohup /usr/local/kcptun/server_linux_amd64 -c /usr/local/kcptun/kcptun-config.json &
