--- # install the shadowsocks
- name: shadowsocks -> download the source codes
  command: git clone "{{ shadowsocks_url }}"
  args:
    chdir: "/root"
    creates: "{{ shadowsocks_path }}"

- name: shadowsocks -> upgrade the source codes
  command: git submodule update --init --recursive
  args:
    chdir: "{{ shadowsocks_path }}"

- name: shadowsocks -> run the init bash
  shell: ./autogen.sh
  args:
    chdir: "{{ shadowsocks_path }}"

- name: shadowsocks -> configure
  command: ./configure
  args:
    chdir: "{{ shadowsocks_path }}"

- name: shadowsocks -> make
  make:
    chdir: "{{ shadowsocks_path }}"

- name: shadowsocks -> make install
  make:
    chdir: "{{ shadowsocks_path }}"
    target: install
