---
webserver:
  hosts:
    centos-demo-1:
      ansible_user: centos-demo-1
      ansible_host: "{{ demo_1_host }}"
      ansible_port: 22
      ansible_password: "{{ demo_1_password }}"
      ansible_ssh_private_key_file: /home/centos-control/.ssh/id_rsa
      ansible_become: true
      ansible_become_user: root
      ansible_become_method: sudo
      ansible_become_password: "{{ demo_1_password }}"
...