--- # install the libsodium
- name: libsodium -> check if the codes exist
  stat:
    path: "{{ libsodium_path }}.tar.gz"
  register: libsodium_code

- name: libsodium -> download the source codes
  get_url:
    url: "{{ libsodium_url }}"
    dest: "{{ libsodium_path }}.tar.gz"
  when: not libsodium_code.stat.exists

- name: libsodium -> create the libsodium directory
  file:
    path: "{{ libsodium_path }}"
    state: directory
    mode: '0744'

- name: libsodium -> unarchive the package
  unarchive:
    remote_src: yes
    src: "{{ libsodium_path }}.tar.gz"
    dest: "{{ libsodium_path }}"

- name: libsodium -> configure the package
  shell: ./configure --prefix=/usr
  args:
    chdir: "{{ libsodium_untar_path }}"
    creates: config.status

- name: libsodium -> make
  make:
    chdir: "{{ libsodium_untar_path }}"

- name: libsodium -> make install
  make:
    chdir: "{{ libsodium_untar_path }}"
    target: install

- name: libsodium -> ldconfig
  command: ldconfig
  args:
    chdir: "{{ libsodium_untar_path }}"
