--- # install the libsodium
- name: download the source codes
  get_url:
    url: "{{ libsodium_url }}"
    dest: "{{ libsodium_path }}.tar.gz"

- name: unarchive the package
  unarchive:
    remote_src: yes
    src: "{{ libsodium_path }}.tar.gz"
    dest: {{ libsodium_path }}

- name: configure the package
  shell: ./configure --prefix=/usr
  args:
    chdir: {{ libsodium_path }}
    creates: config.status

- name: make
  make:
    chdir: {{ libsodium_path }}

- name: make install
  make:
    chdir: {{ libsodium_path }}
    target: install

- name: ldconfig
  command: ldconfig
  args:
    chdir: {{ libsodium_path }}
