--- # install the mbedtls
- name: download the source codes
  get_url:
    url: "{{ mbedtls_url }}"
    dest: "{{ mbedtls_path }}.tar.gz"

- name: create the mbedtls directory
  file:
    path: "{{ mbedtls_path }}"
    state: directory
    mode: '0744'

- name: unarchive the package
  unarchive:
    remote_src: yes
    src: "{{ mbedtls_path }}.tar.gz"
    dest: "{{ mbedtls_path }}"

# gcc version < 5.0 需要强制使用c99标准
# gcc version > 5.0 comand: make SHARED=1 CFLAGS=-fPIC
- name: make
  command:  CC='gcc --std=c99' make
  args:
    chdir: "{{ mbedtls_untar_path }}"

- name: make install
  make:
    chdir: "{{ mbedtls_untar_path }}"
    target: install
    params:
      DESTDIR: /usr

- name: ldconfig
  command: ldconfig
  args:
    chdir: "{{ mbedtls_untar_path }}"
